#!/bin/sh 

output="Volume"
master=$(amixer get Master | tail -1)
active=$(echo "$master" | awk "{print \$6}")
volume=$(echo "$master" | awk "{print \$5}")
    
# Check if headphone is connected
if [ "$(amixer -c0 get Headphone | tail -1 | awk "{print \$6}")" != "[-65.25dB]" ]; then
    output="Headphone"
fi

if [ "$active" = "[off]" ]; then
    echo "${output}: muted"
else
    echo "${output}: ${volume}"
fi

